services:
  mongodb:
    container_name: embulk-input-mongodb_server
    image: mongo:8.0
    restart: always
    ports:
    - 27017:27017
    - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: tiger
    command: --config /etc/mongo/mongod.conf
    volumes:
    - mongodb-data:/data/db
    - mongodb-configdb:/data/configdb
    - ./src/test/resources/:/etc/mongo/
    - ./src/test/resources/initdb.d/:/docker-entrypoint-initdb.d/
  mongodb-4_0:
    container_name: embulk-input-mongodb_server_4_0
    image: mongo:4.0
    restart: always
    ports:
    - 37017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: tiger
    command: --config /etc/mongo/mongod-4.0.conf
    volumes:
    - ./src/test/resources/:/etc/mongo/
    - ./src/test/resources/initdb.d/:/docker-entrypoint-initdb.d/
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: tiger
      ME_CONFIG_MONGODB_SERVER: mongodb
volumes:
  mongodb-data:
    driver: local
  mongodb-configdb:
    driver: local
